### ISSUE TITLE
next-task algorithm API design

### ISSUE THREAD

**Issue by jorgeramirez** [TrentoCrowdAI/crowdai#1]
Currently, the next-task flow (next-task.js file) deal with quality management and the next-task generation logic. We can break it down into: 

* quality management module that generates initial tests and honeypots.
* next task service that generates the tasks (array of items + criteria)
* the current next-task.js module will be responsible for gluing everything together: stop condition, quality management, and task generation.

A very quick draft of the next-task service can be:

```
nextTask(experimentId, workerId, batch=10)

RESPONSE
{ 
    items: [1, 2, 3, 4, 5, 6, ...]
    criteria: [1]
}
```

The above function needs the following:

* A service that given the experiment id returns the available criteria. Available criteria are the ones that have not been applied to all items yet.

```
getAvailableCriteria(experimentId)

RESPONSE
[1, 2, 3, 4, 5, 6]
```

* A service that given the experiment id, the worker and the assigned criteria, returns a list of items with the current number of votes computed (sorted by votes).

```
getAvailableItems(experimentId, workerId, criteria, sort) 

RESPONSE
[
    {id: 2, votes: 1},
    {id: 1, votes: 3},
    {id: 3, votes: 4}, 
    …
]
```

Then the next task service for baseline can be something like:

```javascript
nextTask(experimentId, workerId, batch=10) {
    let availableCriteria = getAvailableCriteria(experimentId);
    let criteria = randomlyPickOne(availableCriteria);
    let availableItems = getAvailableItems(experimentId, workerId, criteria, ASC);
    let items = pickFirst(availableItems, batch)  // eg, first 10 items.
    return {
	items: items,
	criteria: criteria
    }
}

```

In this case, for the batch size, we put the max number of tasks we want a worker to solve.

What do you think about this? @mbaezpy @Evgeneus @sphoebs @fabiounitn

**Comment by sphoebs** [comment]
I think we need to define the api. what comes in and what comes out. also, we need to define how the state is managed.

what comes in: 


-  a request for what is next for worker W, task T. Worker is qualified by ID. task is also qualified by a few parameters the algo might need. we can keep this open for now. 
-  a reference to the state (all previous responses).

I think we can refer to the state as opposed to notifying it each time. thoughts?

the reply is an array of <item, [filters]>

filters is an array as in general case one can ask to processmore than one filter, though our main approach is to go by filter.

also: the box will need to know if a worker dropped out, otherwise we are waiting for the anser by this guy and not assigning items to others. 

both the box and the engine needs to be aware of this issue.
this may be another message to the box, like, worker dropped out, and there are unfinished tasks.

**Comment by jorgeramirez** [comment]
With @Evgeneus we think the following as a proposal for the API. But, first some terminology about the application.

* experiment: represent a screening run, with this, we can get access to the state of the screening process so far. For instance, querying the answers from all workers or from a particular worker, get the items for the experiments, the filters, etc.
* worker: represents a worker coming from Mechanical Turk, we can identify him by their ID.

There will be a module responsible for managing the screening run, I will just call it experiment-flow. This module will:

* Check if the worker is new to the screening run, if so, then run initial tests by calling the quality management module.
* If the worker is not new to the screening run, then this module will check if honeypot task should be returned (again, using quality management module) or if it should call the next-task API to get the task for the worker.
* if the worker already reached the Max Tasks parameter, then it will just return something that indicates we are done with the worker.

The next-task API would look like this:

```
GET /next-task?experimentId=<experiment id>&workerId=<worker id> 
```

Then the response would look like this

 1)
```
{
    items: <item id>
    criteria: [array of criteria id]
}
```
or 

2)
```
{items: 0}
```
(2) means that we should stop the screening run because we are done.

With a response like (1), the experiment-flow module will be able to return a response like the following:
```
{
    item: {description: 'the paper abstract', title: 'the paper title'}
    criteria: [{label: 'C1', description: 'does this paper describe YYYYY?'}],
    isTest: true | false
}
```
Calling the next-task service every time allows to

* Consider how the state of the screening run evolves, for instance, do not consider items that are already labeled (because one worker can be slower than others).
* Take into account how algorithm parameters change: the difficulty of a criterion, accuracy of workers, etc.

The next-task service assumes that there are utility services available: 

* for retrieving the available items for the given experiment. For example, this service would look like

```
GET /experiments/:experimentId/items/?workerId=<worker id>&votes=true
```
The above means, give me the items for the experiment and take into account the items already screened by the worker and include the current votes for each particular item. The response would be something like

```
[
    {itemId: 1, votes: 2},
    {itemId: 3, votes: 5},
    ...
]
```

* for retrieving the available criteria for the worker

```
GET /experiments/:experimentId/criteria?workerId=<worker id>
```
The above would return the available criteria to assign to the worker, or if the worker already has a criterion assigned it will just return it.

```
[
   {criteriaId: 1},
   {criteriaId: 2}
   ...
]
```

To wrap it up, the next-task service:

```
nextTask(workerId, experimentId) -> (item, [filter])
```
or
```
nextTask(workerId, experimentId) -> 0
```

what do you think?
