### ISSUE TITLE
Define Reporting API

### ISSUE THREAD

**Issue by sphoebs** [TrentoCrowdAI/crowdai#9]

**Comment by mattiapv** [comment]
Which information are expected from the Reports?
This come from the very first meeting with Jorge and you.

- Time to complete each task.
- % succcesses
- Agreement
- Agreement in errors?

What else can add?

**Comment by mattiapv** [comment]
This is a list of information the reports page should return so far:

**Reports for requesters**

1.  Time to complete each task:
2.  % successes
3.  Agreement, Agreement in errors, agreement information.
4.  List of items with the classification decision and class probability
5.  Avg, mean and std time taken per task
6.  Avg, mean std number of tasks per worker
7. Num and percentage of workers who failed the initial test
8. Num and percentage of workers who fail at honeypots

This in an idea for the first 2 points.

1)  **Time to complete each task**:

* The requesters can sort by individual jobs:

  List of all job with the worker name associated to it and time to compleate each individual task. So if each job is associated to a worker and contains n tasks:

  * job_number1 - worker_name

        | task1 | task1_time |

        | task2 | task2_time |

        | taskn | taskn_time |

* The requesters can sort by individual tasks:

      | task1 | average_time

2)  **% successes**

* The requesters can sort by workers. Example:

      worker_name | total_job | %of success (considering all jobs he did)

* The requesters can sort by workers and jobs Example:

  worker_name

      job_number1 | %of success
      job_number2 | %of success

* The requesters can sort by individual tasks. Example:

      task1 | average %of success

Could someone explain better point 3 please? @sphoebs @jorgeramirez @mbaezpy @Evgeneus 

Avg and mean in point 5 and 6 isn't the same thing? @sphoebs

**Comment by sphoebs** [comment]
point 5: sorry i meant median

**Comment by nicobell** [comment]
@sphoebs 
For now, we have tried to design the way a requester can access to the Reports page of his/her Projects.
I think that a new Menu Tab could be useful to get there quickly, where the requester can select his Projects and a specific Job (for now just one) to access specific statistics.
![reports_page1](https://user-images.githubusercontent.com/32127539/37901451-89cfb422-30f1-11e8-8ce2-9cf722cc13b9.png)

Once selected, in the Charting page, many metrics will be available to be displayed in graphs.
Those are just examples for the Total Time per Task (just to see the starting page composition).
I'm working in refining the Chart to display data with more details.
![first_chart](https://user-images.githubusercontent.com/32127539/37901666-3eafb2c0-30f2-11e8-8ff5-32e9cf6de6d0.png)
![reports_page](https://user-images.githubusercontent.com/32127539/37901670-40bed8ca-30f2-11e8-9ea6-e4037a6c6aec.png)

**Comment by sphoebs** [comment]
i think it makes sense
any progress on the agreement side?
F

**Comment by nicobell** [comment]
That's a first draw of the Agreement metric,
On the y axis  every couple of data is "item_id,filter_id" and on every bar is represented how worker that submitted that task voted for it (we assumed that every filter has just 3 possible values to choose)

![stacked1](https://user-images.githubusercontent.com/32127539/38543926-4377c832-3ca6-11e8-81a9-a8aa799afb4d.png)

Next task is to define how to display data when a bar is clicked, here we may fetch data about agreement and agreement in errors for that specific task

**Comment by sphoebs** [comment]
grazie, partiamo prima da una cosa piu; semplice, mi fate vedere le metriche anche senza charts, tipo di metrica (eg fleiss) e i numeri?

Fabio
